name: SEND_MSG

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo "{\"text\":\"testing github action :tada:\"}" > mattermost.json

    - uses: cpanato/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
