name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo "{\"text\":\"testing github action :tada:\"}" > mattermost.json
        echo test, and deploy your project.
    - uses: cpanato/action-mattermost-notify@master
      with:
        secrets: ["MATTERMOST_WEBHOOK_URL"]
